spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adoworkers
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

token:
  secret: sigurnost
  expire: 2h

aws:
  access-key: minioadmin
  secret-key: minioadmin
  host: http://localhost:9000
  region: US_EAST_1
  bucket-name: workers
  link-duration: 1h

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://db:3306/workersdb
    username: platform
    password: platform
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  access-key: workers-platform
  secret-key: workers-platform
  host: http://minio:9000
  region: US_EAST_1
  bucket-name: workers
  link-duration: 1h